version: "3.8"

services:
  web:
    build: .
    container_name: Leaf_Lore_Backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://leaf_lore_admin:leaf_lore_1927@db:5432/leaf_lore_dev
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: leaf_lore_db
    environment:
      - POSTGRES_USER=leaf_lore_admin
      - POSTGRES_PASSWORD=leaf_lore_1927
      - POSTGRES_DB=leaf_lore_dev
    ports:
      - "5432:5432"
    volumes:
      - leaf_lore_backend_data:/var/lib/postgresql/data

volumes:
  leaf_lore_backend_data:
