services:
  - name: fastapi-app
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-db
          property: connectionString

  - name: postgresql-db
    type: database
    env: docker
    image: postgres:16
    envVars:
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
    ports:
      - port: 5432
        protocol: TCP
