"""SAM, PredictionLog and UUID

Revision ID: 101d94693ebd
Revises: 9280c9426784
Create Date: 2024-06-02 11:53:16.027796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101d94693ebd'
down_revision: Union[str, None] = '9280c9426784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apex_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Apexes_apex_name'), 'Apexes', ['apex_name'], unique=True)
    op.create_index(op.f('ix_Apexes_id'), 'Apexes', ['id'], unique=False)
    op.create_table('Margins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('margin_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Margins_id'), 'Margins', ['id'], unique=False)
    op.create_index(op.f('ix_Margins_margin_name'), 'Margins', ['margin_name'], unique=True)
    op.create_table('Shapes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shape_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Shapes_id'), 'Shapes', ['id'], unique=False)
    op.create_index(op.f('ix_Shapes_shape_name'), 'Shapes', ['shape_name'], unique=True)
    op.create_table('PredictionLogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('specie_id', sa.UUID(), nullable=True),
    sa.Column('shape_id', sa.UUID(), nullable=True),
    sa.Column('apex_id', sa.UUID(), nullable=True),
    sa.Column('margin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['apex_id'], ['Apexes.id'], ),
    sa.ForeignKeyConstraint(['margin_id'], ['Margins.id'], ),
    sa.ForeignKeyConstraint(['shape_id'], ['Shapes.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['Species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PredictionLogs_id'), 'PredictionLogs', ['id'], unique=False)
    op.create_index(op.f('ix_PredictionLogs_image_name'), 'PredictionLogs', ['image_name'], unique=True)
    op.add_column('MappedImages', sa.Column('shape_id', sa.UUID(), nullable=True))
    op.add_column('MappedImages', sa.Column('apex_id', sa.UUID(), nullable=True))
    op.add_column('MappedImages', sa.Column('margin_id', sa.UUID(), nullable=True))
    op.alter_column('MappedImages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"MappedImages_id_seq"\'::regclass)'))
    op.alter_column('MappedImages', 'specie_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('MappedImages', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'MappedImages', 'Apexes', ['apex_id'], ['id'])
    op.create_foreign_key(None, 'MappedImages', 'Shapes', ['shape_id'], ['id'])
    op.create_foreign_key(None, 'MappedImages', 'Margins', ['margin_id'], ['id'])
    op.alter_column('Species', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Species_id_seq"\'::regclass)'))
    op.alter_column('Users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'))
    op.alter_column('Species', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"Species_id_seq"\'::regclass)'))
    op.drop_constraint(None, 'MappedImages', type_='foreignkey')
    op.drop_constraint(None, 'MappedImages', type_='foreignkey')
    op.drop_constraint(None, 'MappedImages', type_='foreignkey')
    op.alter_column('MappedImages', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('MappedImages', 'specie_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('MappedImages', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"MappedImages_id_seq"\'::regclass)'))
    op.drop_column('MappedImages', 'margin_id')
    op.drop_column('MappedImages', 'apex_id')
    op.drop_column('MappedImages', 'shape_id')
    op.drop_index(op.f('ix_PredictionLogs_image_name'), table_name='PredictionLogs')
    op.drop_index(op.f('ix_PredictionLogs_id'), table_name='PredictionLogs')
    op.drop_table('PredictionLogs')
    op.drop_index(op.f('ix_Shapes_shape_name'), table_name='Shapes')
    op.drop_index(op.f('ix_Shapes_id'), table_name='Shapes')
    op.drop_table('Shapes')
    op.drop_index(op.f('ix_Margins_margin_name'), table_name='Margins')
    op.drop_index(op.f('ix_Margins_id'), table_name='Margins')
    op.drop_table('Margins')
    op.drop_index(op.f('ix_Apexes_id'), table_name='Apexes')
    op.drop_index(op.f('ix_Apexes_apex_name'), table_name='Apexes')
    op.drop_table('Apexes')
    # ### end Alembic commands ###
