"""rename image_name to image_path

Revision ID: 1e9e9ee7d8c3
Revises: 254b6f2f6795
Create Date: 2024-06-07 18:58:51.934297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9e9ee7d8c3'
down_revision: Union[str, None] = '254b6f2f6795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MappedImages', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_index('ix_MappedImages_image_name', table_name='MappedImages')
    op.create_index(op.f('ix_MappedImages_image_path'), 'MappedImages', ['image_path'], unique=True)
    op.drop_column('MappedImages', 'image_name')
    op.add_column('PredictionLogs', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_index('ix_PredictionLogs_image_name', table_name='PredictionLogs')
    op.create_index(op.f('ix_PredictionLogs_image_path'), 'PredictionLogs', ['image_path'], unique=True)
    op.drop_column('PredictionLogs', 'image_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PredictionLogs', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_PredictionLogs_image_path'), table_name='PredictionLogs')
    op.create_index('ix_PredictionLogs_image_name', 'PredictionLogs', ['image_name'], unique=True)
    op.drop_column('PredictionLogs', 'image_path')
    op.add_column('MappedImages', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_MappedImages_image_path'), table_name='MappedImages')
    op.create_index('ix_MappedImages_image_name', 'MappedImages', ['image_name'], unique=True)
    op.drop_column('MappedImages', 'image_path')
    # ### end Alembic commands ###
