"""initial migration

Revision ID: 254b6f2f6795
Revises: 
Create Date: 2024-06-07 18:57:04.642679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254b6f2f6795'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apex_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Apexes_apex_name'), 'Apexes', ['apex_name'], unique=True)
    op.create_index(op.f('ix_Apexes_id'), 'Apexes', ['id'], unique=False)
    op.create_table('Margins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('margin_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Margins_id'), 'Margins', ['id'], unique=False)
    op.create_index(op.f('ix_Margins_margin_name'), 'Margins', ['margin_name'], unique=True)
    op.create_table('Shapes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shape_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Shapes_id'), 'Shapes', ['id'], unique=False)
    op.create_index(op.f('ix_Shapes_shape_name'), 'Shapes', ['shape_name'], unique=True)
    op.create_table('Species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Species_class_number'), 'Species', ['class_number'], unique=True)
    op.create_index(op.f('ix_Species_common_name'), 'Species', ['common_name'], unique=False)
    op.create_index(op.f('ix_Species_id'), 'Species', ['id'], unique=False)
    op.create_index(op.f('ix_Species_scientific_name'), 'Species', ['scientific_name'], unique=True)
    op.create_table('Users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_name'), 'Users', ['name'], unique=True)
    op.create_index(op.f('ix_Users_role'), 'Users', ['role'], unique=False)
    op.create_table('MappedImages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('specie_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('shape_id', sa.UUID(), nullable=True),
    sa.Column('apex_id', sa.UUID(), nullable=True),
    sa.Column('margin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['apex_id'], ['Apexes.id'], ),
    sa.ForeignKeyConstraint(['margin_id'], ['Margins.id'], ),
    sa.ForeignKeyConstraint(['shape_id'], ['Shapes.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['Species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MappedImages_id'), 'MappedImages', ['id'], unique=False)
    op.create_index(op.f('ix_MappedImages_image_name'), 'MappedImages', ['image_name'], unique=True)
    op.create_table('PredictionLogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('specie_id', sa.UUID(), nullable=True),
    sa.Column('shape_id', sa.UUID(), nullable=True),
    sa.Column('apex_id', sa.UUID(), nullable=True),
    sa.Column('margin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['apex_id'], ['Apexes.id'], ),
    sa.ForeignKeyConstraint(['margin_id'], ['Margins.id'], ),
    sa.ForeignKeyConstraint(['shape_id'], ['Shapes.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['Species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PredictionLogs_id'), 'PredictionLogs', ['id'], unique=False)
    op.create_index(op.f('ix_PredictionLogs_image_name'), 'PredictionLogs', ['image_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PredictionLogs_image_name'), table_name='PredictionLogs')
    op.drop_index(op.f('ix_PredictionLogs_id'), table_name='PredictionLogs')
    op.drop_table('PredictionLogs')
    op.drop_index(op.f('ix_MappedImages_image_name'), table_name='MappedImages')
    op.drop_index(op.f('ix_MappedImages_id'), table_name='MappedImages')
    op.drop_table('MappedImages')
    op.drop_index(op.f('ix_Users_role'), table_name='Users')
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Species_scientific_name'), table_name='Species')
    op.drop_index(op.f('ix_Species_id'), table_name='Species')
    op.drop_index(op.f('ix_Species_common_name'), table_name='Species')
    op.drop_index(op.f('ix_Species_class_number'), table_name='Species')
    op.drop_table('Species')
    op.drop_index(op.f('ix_Shapes_shape_name'), table_name='Shapes')
    op.drop_index(op.f('ix_Shapes_id'), table_name='Shapes')
    op.drop_table('Shapes')
    op.drop_index(op.f('ix_Margins_margin_name'), table_name='Margins')
    op.drop_index(op.f('ix_Margins_id'), table_name='Margins')
    op.drop_table('Margins')
    op.drop_index(op.f('ix_Apexes_id'), table_name='Apexes')
    op.drop_index(op.f('ix_Apexes_apex_name'), table_name='Apexes')
    op.drop_table('Apexes')
    # ### end Alembic commands ###
